version: '3.7'
services:
  mysql_container:
    image: mysql:latest
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./src/main/resources/app.env
    ports:
      - "3306:3306"
    volumes:
      - mysqlDB:/var/lib/mysql
    networks:
      - adopet_network
  adminer_container:
    image: adminer:latest
    container_name: adminer_ui
    environment:
      ADMINER_DEFAULT_SERVER: mysql_container
    ports:
      - "8081:8080"
    networks:
      - adopet_network
volumes:
  mysqlDB:
networks:
  adopet_network: