spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cb6
    username: mysql
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: admin

server:
  port: 8082

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

