spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cb6
    username: mysql
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
