spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cb6
    username: mysql
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  security:
    user:
      name: admin

server:
  port: 8082
  servlet:
    context-path: /adopet

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
